# Generated by Django 2.2.5 on 2019-09-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190925_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='created',
        ),
    ]
