# Generated by Django 2.2.5 on 2019-09-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190925_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.IntegerField(default=1, verbose_name='评论级别'),
        ),
    ]
